config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :images
  resources :users, only: [:show, :destroy], :constraints => { :id => /[0-9|]+/ }
  devise_for :users, :controllers => { :registrations => 'registrations' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, PictureUploader
end

app/models/payment.rb
class Payment < ApplicationRecord
  attr_accessor :card_number, :card_cvc, :card_expires_month, :card_expires_year
  belongs_to :user

  def self.month_options
    Date::MONTHNAMES.compact.each_with_index.map { |name, i| ["#{i+1} - #{name}", i+1]}
  end

  def self.year_options
    (Date.today.year..(Date.today.year + 10)).to_a
  end

  def process_payment
    customer = Stripe::Customer.create email: email, card: token

    Stripe::Charge.create customer: customer.id,
                          amount: 1000,
                          description: 'Premium',
                          currency: 'usd'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_one :payment
  has_many :images
  accepts_nested_attributes_for :payment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user = current_user

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:name, :picture, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)

    resource.class.transaction do
      resource.save
      yield resource if block_given?
      if resource.persisted?
        @payment = Payment.new({ email: params['user']['email'],
          token: params[:payment]['token'], user_id: resource.id })

        flash[:error] = 'Please check registration errors' unless @payment.valid?

        begin
          @payment.process_payment
          @payment.save
        rescue Exception => e
          flash[:error] = e.message
          resource.destroy
          puts 'Payment failed'
          render :new and return
        end

        if resource.active_for_authentication?
          set_flash_message :notice, :signed_up if is_flashing_format?
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
      else
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:payment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/images/_form.html.erb
<%= form_for @image, :html => { multipart: true, :class => "form-horizontal image" } do |f| %>

  <% if @image.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @image.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :picture, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </div>
    <%=f.error_span(:picture) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                images_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/images/edit.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/index.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:picture) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= link_to image.id, image_path(image) %></td>
        <td><%= image.name %></td>
        <td><%= image_tag(image.picture.url, size: "100x100") if image.picture? %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_image_path(image), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      image_path(image),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_image_path,
            :class => 'btn btn-primary' %>

app/views/images/new.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/show.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @image.name %></dd>
  <dd><%= image_tag(@image.picture.url, size: "300x300") if @image.picture? %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              images_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_image_path(@image), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              image_path(@image),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/_navigation.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "PhotoApp", root_path, class: "navbar-brand header-link menu" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <% if user_signed_in? %>
        <ul class="navbar-nav mr-auto menu">
          <li class="nav-item">
            <a class="nav-link" href="#">Users</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Photos
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to new_image_path, class: 'dropdown-item' do %>
                <%= fa_icon 'camera' %> Add photo
              <% end %>
              <%= link_to images_path, class: 'dropdown-item' do %>
                <%= fa_icon 'picture-o' %> View photos
              <% end %>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to edit_user_registration_path(current_user), class: 'dropdown-item' do %>
                <%= fa_icon 'edit' %> Edit
              <% end %>
              <%= link_to user_path(current_user), class: 'dropdown-item', method: :delete, data: { confirm: 'Are you sure that you want delete your profile? This action is not reversible and your stocks and friends list will be dropped.' } do %>
                <%= fa_icon 'trash' %> Delete
              <% end %>
            </div>
          </li>
        </ul>
        <ul class='navbar-nav navbar-right'>
          <li class='nav-item user-name'>
            <%= fa_icon 'user' %> <span class="badge badge-pill badge-info"><%= current_user.email %></span>
          </li>
          <li class='nav-item'>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger auth-button'%>
          </li>
        </ul>
      <% else %>
        <ul class='navbar-nav navbar-right'>
          <li class='nav-item'>
            <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary auth-button'%>
          </li>
          <li class='nav-item'>
            <%= link_to 'Login', new_user_session_path, class: 'btn btn-success auth-button'%>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PhotoApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <%= render "layouts/navigation" %>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2020</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h2>Welcome to the Photo Management App!</h2>
  <p class="lead">
    You'll love managing your Photos with our application.
  </p>
</div>
<% unless current_user %>
  <div class="card-group">
    <div class="card bg-light mb-3">
      <div class="card-header">
        Premium Plan
      </div>
      <div class="card-body">
        <h5 class="card-title">Price: $10</h5>
        <ul>
          <li>Unlimited Image Uploads</li>
          <li>Responsive design</li>
          <li>Access anywhere</li>
        </ul>
        <%= link_to 'Join', new_user_registration_path, class: 'btn btn-lg btn-primary sign-up' %>
      </div>
    </div>
    <div class="card bg-light mb-3">
      <div class="card-header">
        Gold Plan
      </div>
      <div class="card-body">
        <h5 class="card-title">Price: $20</h5>
        <ul>
          <li>Unlimited Image Uploads</li>
          <li>Responsive design</li>
          <li>Access anywhere</li>
          <li class='extra'>Unlimited projects</li>
        </ul>
        <%= link_to 'Join', new_user_registration_path, class: 'btn btn-lg btn-primary sign-up' %>
      </div>
    </div>
  </div>
<% end %>